#!/usr/bin/env python
"""GritAI Discord AI Bot — a real assistant living in a Discord server (30-in-15 · #11).

Talk to it by @mentioning it in a channel or DMing it; or use the /ask slash command. Replies are
generated by brain.generate() (safety-gated, memory-aware) — backed by our own local GPU fleet by
default (free, private), or Claude if configured.

Run:
  pip install -r requirements.txt
  export DISCORD_BOT_TOKEN=...          # from the Discord Developer Portal
  python bot.py

Requires the "Message Content Intent" enabled on the bot (Developer Portal → Bot → Privileged Intents)
so it can read messages that mention it.
"""
import os, time, asyncio


def _load_env(path):
    """Minimal .env loader (stdlib only). Runs BEFORE `import brain`, which reads its
    config at import time. Does not override vars already set in the real environment."""
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, _, v = line.partition("=")
                os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))
    except FileNotFoundError:
        pass


_load_env(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))

import discord
from discord import app_commands

import brain

TOKEN = os.environ.get("DISCORD_BOT_TOKEN", "").strip()
COOLDOWN = float(os.environ.get("BOT_COOLDOWN_SECONDS", "3"))   # per-user min seconds between requests

intents = discord.Intents.default()
intents.message_content = True   # privileged — enable in the Developer Portal
client = discord.Client(intents=intents)
tree = app_commands.CommandTree(client)

_last = {}   # user_id -> monotonic ts (lightweight per-user rate limit)


def _rate_limited(user_id: int) -> bool:
    now = time.monotonic()
    if now - _last.get(user_id, 0) < COOLDOWN:
        return True
    _last[user_id] = now
    return False


def _key(message: discord.Message) -> str:
    # One conversation memory per channel (DMs get their own channel id).
    return f"ch:{message.channel.id}"


async def _think_and_reply(message: discord.Message, prompt: str):
    async with message.channel.typing():
        reply = await asyncio.to_thread(brain.generate, _key(message), prompt)
    await message.reply(reply, mention_author=False)


@client.event
async def on_ready():
    try:
        await tree.sync()
    except Exception as e:
        print(f"slash sync error: {type(e).__name__}")
    print(f"{client.user} online — in {len(client.guilds)} server(s). Backend={brain.BACKEND}")


def _my_ids(message: discord.Message):
    """Every id that counts as 'me' in a mention: the bot user, plus the managed
    integration role Discord auto-creates for the bot (which @-autocomplete often
    picks instead of the bot user)."""
    ids = [client.user.id]
    if message.guild and message.guild.me:
        ids += [r.id for r in message.guild.me.roles if r.managed]
    return ids


def _mentions_me(message: discord.Message) -> bool:
    if client.user in message.mentions:
        return True
    if message.guild and message.guild.me:
        mine = {r.id for r in message.guild.me.roles if r.managed}
        if any(r.id in mine for r in message.role_mentions):
            return True
    return False


@client.event
async def on_message(message: discord.Message):
    if message.author.bot:
        return   # never talk to other bots (loop-safe)
    is_dm = message.guild is None
    if not (is_dm or _mentions_me(message)):
        return
    if _rate_limited(message.author.id):
        return
    # strip the bot's user- and role-mention tokens out of the text
    prompt = message.content
    for i in _my_ids(message):
        for m in (f"<@{i}>", f"<@!{i}>", f"<@&{i}>"):
            prompt = prompt.replace(m, "")
    prompt = prompt.strip()
    if not prompt:
        prompt = "hello"
    print(f"[msg] replying to {message.author} in {'DM' if is_dm else '#'+message.channel.name}")
    try:
        await _think_and_reply(message, prompt)
    except Exception as e:
        print(f"on_message error: {type(e).__name__}")


@tree.command(name="ask", description="Ask the GritAI bot a question")
@app_commands.describe(question="What do you want to ask?")
async def ask(interaction: discord.Interaction, question: str):
    if _rate_limited(interaction.user.id):
        await interaction.response.send_message("Easy there — give me a couple seconds between questions.",
                                                ephemeral=True)
        return
    await interaction.response.defer(thinking=True)
    reply = await asyncio.to_thread(brain.generate, f"ch:{interaction.channel_id}", question)
    await interaction.followup.send(reply)


@tree.command(name="reset", description="Clear the bot's memory of this channel's conversation")
async def reset(interaction: discord.Interaction):
    brain.reset(f"ch:{interaction.channel_id}")
    await interaction.response.send_message("🧠 Memory cleared for this channel.", ephemeral=True)


@tree.command(name="help", description="What can this bot do?")
async def help_cmd(interaction: discord.Interaction):
    await interaction.response.send_message(
        f"**{brain.BOT_NAME}** — @mention me or DM me to chat, or use `/ask`. I remember the last few "
        "messages per channel. `/reset` clears my memory here. Built by GritAI Solutions, running on our "
        "own GPU fleet.", ephemeral=True)


if __name__ == "__main__":
    if not TOKEN:
        raise SystemExit("Set DISCORD_BOT_TOKEN (Discord Developer Portal → Bot → Reset Token).")
    client.run(TOKEN)
